
import '../assets/cssreset.css';
import '../assets/bootstrap-grid.css'
import './globals.css'
import Header from './compnents/Header/Header';

export const metadata = {
  title: 'Recepies',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
          <body>
            <Header />
            {children}
          </body>
      </html>
    </>
  );
}
